import type { Playbook } from "./types";

const now = new Date().toISOString();
const day = 86400000;

export const mockPlaybooks: Playbook[] = [
  {
    id: "pb_1",
    title: "ICT Killzone Entry",
    description: "Trade the institutional killzone during London and New York opens using fair value gaps and order blocks.",
    category: "ict",
    tags: ["ICT", "Killzone", "FVG", "Order Block"],
    market: ["forex", "indices"],
    timeframes: ["15m", "1h", "4h"],
    riskProfile: "medium",
    difficulty: "advanced",
    expectedRR: 3,
    winRate: 68,
    totalTrades: 142,
    netProfit: 28400,
    avgRR: 2.8,
    expectancy: 1.4,
    maxDrawdown: 12,
    consistencyScore: 76,
    setup: {
      marketConditions: "Liquidity sweep above previous day high during London open. 15m FVG formed after the sweep. Price returns to FVG with 1h OB confluence.",
      entryRules: [
        "Wait for liquidity sweep of previous day high/low",
        "Identify 15m FVG after the sweep",
        "Entry on 15m FVG touch with 1h order block confluence",
        "Entry must be during London (02:00-05:00 EST) or NY (07:00-10:00 EST) killzone",
      ],
      confirmationRules: [
        "15m bullish engulfing candle at FVG touch",
        "RSI divergence on 15m",
        "Volume spike on entry candle",
      ],
      invalidationRules: [
        "Price fails to hold FVG after 2 candles",
        "No displacement candle within 3 candles",
        "Higher timeframe trend opposes entry",
      ],
      stopLossRules: [
        "SL below order block low (1h)",
        "SL at 1.5x ATR from entry",
        "Never risk more than 1% per trade",
      ],
      takeProfitRules: [
        "First TP at previous day high/low (1:1)",
        "Second TP at weekly open (1:2)",
        "Third TP at weekly high/low (1:3)",
        "Scale out 40% at TP1, 30% at TP2, 30% at TP3",
      ],
      managementRules: [
        "Move SL to breakeven after TP1 hit",
        "Trail SL at 0.5x ATR after TP2",
        "If price stalls at TP2 for 3+ candles, close remaining",
      ],
      riskRules: [
        "1% risk per trade maximum",
        "Max 2 consecutive losses → stop trading for 4 hours",
        "No trading during low-impact news",
        "Reduce position size by 50% after 3 losses in a day",
      ],
      commonMistakes: [
        "Entering before the sweep completes",
        "Taking trades outside killzone windows",
        "Ignoring higher timeframe trend",
        "Moving SL to breakeven too early",
        "Overtrading after a win streak",
      ],
      checklist: [
        "Higher timeframe trend confirmed?",
        "Liquidity sweep completed?",
        "In killzone window?",
        "FVG identified on 15m?",
        "1h order block confluence?",
        "RSI divergence present?",
        "Risk < 1% of account?",
        "TP levels marked?",
      ],
    },
    examples: [
      { id: "ex_1", type: "winning", title: "EU London Killzone", description: "Textbook EUR/USD London killzone trade. Swept previous day high, created 15m FVG, returned to 1h OB. Hit all 3 TPs for 3R.", screenshots: [], replayLink: "/replay?id=ex_1", pnl: 1200, date: "2026-06-15" },
      { id: "ex_2", type: "losing", title: "GU Early Entry Mistake", description: "Entered GBP/USD before sweep completed. Price continued higher, SL hit. Lesson: patience for full sweep.", screenshots: [], replayLink: "/replay?id=ex_2", pnl: -400, date: "2026-06-18" },
    ],
    versions: [
      { id: "v1", version: 1, timestamp: new Date(Date.now() - day * 30).toISOString(), changes: "Initial version" },
      { id: "v2", version: 2, timestamp: new Date(Date.now() - day * 14).toISOString(), changes: "Added RSI divergence confirmation rule" },
      { id: "v3", version: 3, timestamp: new Date(Date.now() - day * 2).toISOString(), changes: "Updated risk rules for consecutive loss management" },
    ],
    content: "## ICT Killzone Entry\n\nInstitutional killzone trading focuses on capturing price movements during high-liquidity windows when institutional orders enter the market.\n\n### Core Concept\n\nBanks and institutions execute large orders during specific windows. By identifying their footprints (liquidity sweeps, FVGs, order blocks), we can align with their flow.",
    isFavorite: true,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 30).toISOString(),
    updatedAt: new Date(Date.now() - day * 2).toISOString(),
  },
  {
    id: "pb_2",
    title: "Opening Range Breakout",
    description: "Trade the breakout of the first 30-minute range with volume confirmation and momentum filters.",
    category: "breakout",
    tags: ["ORB", "Momentum", "Volume"],
    market: ["stocks", "futures", "indices"],
    timeframes: ["5m", "15m"],
    riskProfile: "medium",
    difficulty: "beginner",
    expectedRR: 2,
    winRate: 72,
    totalTrades: 312,
    netProfit: 46800,
    avgRR: 2.1,
    expectancy: 0.9,
    maxDrawdown: 8,
    consistencyScore: 82,
    setup: {
      marketConditions: "Pre-market volume above 20-day average. No major economic events within 30 minutes. SPY above/below VWAP showing directional bias.",
      entryRules: [
        "Identify first 30-minute high AND low after market open",
        "Wait for candle close outside the 30m range",
        "Entry on limit order at range high + 10c (long) or range low - 10c (short)",
        "Volume on breakout candle must exceed 1.5x avg 5m volume",
      ],
      confirmationRules: [
        "Breakout candle closes outside range",
        "Volume confirmation on breakout candle",
        "RSI above 60 (long) or below 40 (short)",
        "Price above VWAP (long) or below VWAP (short)",
      ],
      invalidationRules: [
        "Price re-enters the 30m range after breakout",
        "False breakout with low volume",
        "Breakout occurs during first 5 minutes (unreliable)",
      ],
      stopLossRules: [
        "SL at opposite end of 30m range",
        "Alternative: SL at 2x ATR from entry",
      ],
      takeProfitRules: [
        "TP1 at 1x range width (scale 50%)",
        "TP2 at 2x range width (scale 50%)",
      ],
      managementRules: [
        "Move SL to breakeven after TP1",
        "Trail remaining position with 1x ATR stop",
      ],
      riskRules: [
        "1% risk per trade",
        "Max 2 ORB trades per day",
        "Skip if first 30m range is less than 0.3% of price",
      ],
      commonMistakes: [
        "Entering before candle close",
        "Trading breakouts during first 5 minutes",
        "Ignoring pre-market volume",
        "Taking trades against VWAP direction",
      ],
      checklist: [
        "Pre-market volume > 20-day average?",
        "30m range clearly defined?",
        "Range width > 0.3% of price?",
        "Breakout candle closed?",
        "Volume confirmation?",
        "VWAP filter aligned?",
        "No major news in 30 min?",
      ],
    },
    examples: [
      { id: "ex_3", type: "winning", title: "ES Opening Range Breakout", description: "S&P 500 futures broke above 30m range with 2x average volume. Ran 2x range to TP2.", screenshots: [], replayLink: "/replay?id=ex_3", pnl: 850, date: "2026-07-10" },
    ],
    versions: [
      { id: "v4", version: 1, timestamp: new Date(Date.now() - day * 60).toISOString(), changes: "Initial version" },
    ],
    content: "## Opening Range Breakout\n\nThe opening range breakout is one of the most reliable intraday strategies. It capitalizes on the initial volatility of the trading session.",
    isFavorite: true,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 60).toISOString(),
    updatedAt: new Date(Date.now() - day * 5).toISOString(),
  },
  {
    id: "pb_3",
    title: "VWAP Mean Reversion",
    description: "Exploit price deviations from VWAP using standard deviation bands for mean reversion entries.",
    category: "scalping",
    tags: ["VWAP", "Mean Reversion", "Scalp"],
    market: ["stocks", "futures"],
    timeframes: ["1m", "5m"],
    riskProfile: "low",
    difficulty: "intermediate",
    expectedRR: 1.5,
    winRate: 78,
    totalTrades: 567,
    netProfit: 42500,
    avgRR: 1.3,
    expectancy: 0.6,
    maxDrawdown: 5,
    consistencyScore: 88,
    setup: {
      marketConditions: "Range-bound market with no clear directional bias. VWAP flattening or sloping slightly. ATR within 10-day average range.",
      entryRules: [
        "Price touches or crosses VWAP +2 std dev band (short) or -2 std dev band (long)",
        "Wait for bullish/bearish divergence on 1m RSI",
        "Entry on limit order at VWAP band",
      ],
      confirmationRules: [
        "RSI divergence on 1m",
        "Candle closes back inside the band",
        "Volume declining near the extreme",
      ],
      invalidationRules: [
        "Price breaks through VWAP on high volume (trend day)",
        "VWAP is steeply sloped (directional bias)",
        "News-driven move (wait for absorption)",
      ],
      stopLossRules: ["SL at +3 std dev band", "Alternative: SL at recent swing high/low"],
      takeProfitRules: ["TP at VWAP (scale 100%)", "Extension TP at -1 std dev band (if strong reversal)"],
      managementRules: ["Scale 50% at VWAP, let rest run to -1 std dev", "If price reaches TP within 3 candles, take full profit"],
      riskRules: ["0.5% risk per trade", "Max 5 trades per session", "No trades in last hour"],
      commonMistakes: ["Trading on trend days", "Entering before RSI divergence confirmed", "Holding through VWAP breakout"],
      checklist: ["Market ranging, not trending?", "VWAP slope flat or gentle?", "Price at 2nd std dev band?", "RSI divergence confirmed?", "Volume declining?", "No major news?"],
    },
    examples: [],
    versions: [{ id: "v5", version: 1, timestamp: new Date(Date.now() - day * 45).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: false,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 45).toISOString(),
    updatedAt: new Date(Date.now() - day * 10).toISOString(),
  },
  {
    id: "pb_4",
    title: "Swing Trend Following",
    description: "Capture larger moves by riding established trends with pullback entries and trailing stops.",
    category: "swing",
    tags: ["Trend", "Pullback", "Swing"],
    market: ["stocks", "crypto", "indices"],
    timeframes: ["1d", "4h"],
    riskProfile: "high",
    difficulty: "intermediate",
    expectedRR: 4,
    winRate: 58,
    totalTrades: 89,
    netProfit: 62300,
    avgRR: 3.8,
    expectancy: 2.2,
    maxDrawdown: 22,
    consistencyScore: 65,
    setup: {
      marketConditions: "Strong uptrend with higher highs and higher lows. Price above all major EMAs (20, 50, 200). ATR expanding. Sector relative strength.",
      entryRules: ["Identify established trend on daily chart", "Wait for pullback to 20 EMA on 4h", "Entry on bullish engulfing candle at 20 EMA touch"],
      confirmationRules: ["RSI above 40 during pullback (bullish)", "Volume declining during pullback, expanding on bounce", "No divergence on daily RSI"],
      invalidationRules: ["Pullback breaks below 50 EMA", "Trendline broken on daily", "RSI drops below 40"],
      stopLossRules: ["SL below the pullback low", "SL at 2x ATR below entry"],
      takeProfitRules: ["Scale 50% at prior swing high", "Trail remaining at 3x ATR", "Exit all on daily close below 20 EMA"],
      managementRules: ["Add 25% position on 2nd pullback if trend intact", "Reduce position by 50% before major earnings/FOMC"],
      riskRules: ["2% risk per trade", "Max 3 open swing trades", "Correlate with SPY direction"],
      commonMistakes: ["Adding too early on pullback", "Not respecting 50 EMA invalidation", "Scaling out too early"],
      checklist: ["Daily uptrend confirmed?", "Above all major EMAs?", "Pullback to 20 EMA on 4h?", "Bullish reversal candle?", "Volume pattern correct?", "RSI filter satisfied?", "Risk 2% or less?"],
    },
    examples: [{ id: "ex_4", type: "winning", title: "NVDA Swing", description: "Caught NVDA pullback to 20EMA during AI rally. Held for 3 weeks, 4.5R.", screenshots: [], pnl: 4500, date: "2026-05-20" }],
    versions: [{ id: "v6", version: 1, timestamp: new Date(Date.now() - day * 90).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: true,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 90).toISOString(),
    updatedAt: new Date(Date.now() - day * 20).toISOString(),
  },
  {
    id: "pb_5",
    title: "Liquidity Grab Reversal",
    description: "Identify liquidity grabs at swing highs/lows and trade the reversal with SMC confirmations.",
    category: "liquidity",
    tags: ["SMC", "Liquidity", "Reversal", "Sweep"],
    market: ["forex", "crypto", "indices"],
    timeframes: ["15m", "1h"],
    riskProfile: "medium",
    difficulty: "advanced",
    expectedRR: 2.5,
    winRate: 64,
    totalTrades: 198,
    netProfit: 35640,
    avgRR: 2.3,
    expectancy: 1.2,
    maxDrawdown: 15,
    consistencyScore: 71,
    setup: {
      marketConditions: "Price approaching previous swing high/low with momentum slowing. OBV diverging from price. Lower timeframe showing exhaustion.",
      entryRules: ["Identify liquidity pool at swing high/low", "Wait for sweep of swing point with low-volume wick", "Entry on return to sweep level with confirmation"],
      confirmationRules: ["Sweep candle has long wick (rejection)", "Volume spike on sweep, then drop on return", "Order block at sweep level holds"],
      invalidationRules: ["Price closes beyond sweep level", "High volume continuation after sweep", "Higher timeframe trend opposes reversal"],
      stopLossRules: ["SL beyond the sweep wick", "SL at 1.5x ATR"],
      takeProfitRules: ["TP1 at next swing point (1:1)", "TP2 at structural order block (1:2.5)"],
      managementRules: ["Breakeven after TP1", "Trail SL at previous candle low/high after TP2"],
      riskRules: ["1% risk per trade", "Avoid during high-impact news", "No reversal against monthly trend"],
      commonMistakes: ["Entering during the sweep", "Sweep too deep (trend continuation)", "No higher timeframe confluence"],
      checklist: ["Swing point identified?", "Low-volume sweep?", "Wick rejection?", "Order block identified?", "Volume declining after sweep?", "HTF trend aligned?"],
    },
    examples: [],
    versions: [{ id: "v7", version: 1, timestamp: new Date(Date.now() - day * 35).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: false,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 35).toISOString(),
    updatedAt: new Date(Date.now() - day * 12).toISOString(),
  },
  {
    id: "pb_6",
    title: "News Momentum Scalp",
    description: "Trade the initial volatility spike after high-impact economic releases with strict risk controls.",
    category: "news",
    tags: ["News", "Scalp", "Momentum", "High Impact"],
    market: ["forex", "indices"],
    timeframes: ["1m", "5m"],
    riskProfile: "high",
    difficulty: "expert",
    expectedRR: 1.5,
    winRate: 55,
    totalTrades: 234,
    netProfit: 18720,
    avgRR: 1.4,
    expectancy: 0.5,
    maxDrawdown: 18,
    consistencyScore: 60,
    setup: {
      marketConditions: "High-impact news event (NFP, CPI, FOMC, GDP). Pre-news ATR above 20-day average. Market expecting a specific outcome.",
      entryRules: ["Wait for initial spike to settle (30-60 seconds post-release)", "Identify direction of first 1m candle after spike", "Entry on retracement to VWAP"],
      confirmationRules: ["First 1m candle closes with momentum", "Retracement holds above/below pre-news level"],
      invalidationRules: ["Price reverses beyond pre-news range", "No clear direction within 2 minutes"],
      stopLossRules: ["SL at pre-news range extreme", "SL at 1x ATR of 5m (whichever is smaller)"],
      takeProfitRules: ["TP at 1.5x risk", "Full exit within 15 minutes"],
      managementRules: ["Move SL to break even after 1:1", "Scale 50% at 1:1, run rest to 1.5"],
      riskRules: ["0.5% risk per trade", "1 trade per news event maximum", "No news trading in first/last hour of session"],
      commonMistakes: ["Entering during initial spike", "Holding too long after the move", "Oversizing due to excitement"],
      checklist: ["High-impact event?", "Initial spike settled?", "Direction identified?", "Retracement to VWAP?", "Risk 0.5% or less?", "Within acceptable hours?"],
    },
    examples: [],
    versions: [{ id: "v8", version: 1, timestamp: new Date(Date.now() - day * 20).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: false,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 20).toISOString(),
    updatedAt: new Date(Date.now() - day * 8).toISOString(),
  },
  {
    id: "pb_7",
    title: "SMC Order Flow",
    description: "Trade using smart money concepts: order blocks, breaker blocks, mitigation, and displacement.",
    category: "smc",
    tags: ["SMC", "Order Block", "Breaker", "Displacement"],
    market: ["forex", "crypto"],
    timeframes: ["1h", "4h"],
    riskProfile: "medium",
    difficulty: "expert",
    expectedRR: 3,
    winRate: 61,
    totalTrades: 156,
    netProfit: 42120,
    avgRR: 2.9,
    expectancy: 1.5,
    maxDrawdown: 14,
    consistencyScore: 73,
    setup: {
      marketConditions: "Market structure shift on higher timeframe. Displacement candle through structure. OB identified at source of displacement.",
      entryRules: ["Wait for displacement candle through structure", "Identify order block at displacement origin", "Entry on retest of order block"],
      confirmationRules: ["Mitigation of displacement (price returns to OB)", "Low-volume retest of OB", "Rejection candle at OB"],
      invalidationRules: ["Price closes below OB (long) or above OB (short)", "No reaction within 5 candles of retest"],
      stopLossRules: ["SL beyond the order block extreme", "SL at 1.5x ATR"],
      takeProfitRules: ["TP1 at most recent swing point", "TP2 at next structural level", "Trail at previous candle low/high"],
      managementRules: ["Partial at TP1", "Move SL to entry after 1:1"],
      riskRules: ["1% risk per trade", "Only in direction of HTF trend", "No trades during news"],
      commonMistakes: ["Confusing displacement with noise", "Entering at wrong OB (not source of displacement)", "No patience for retest confirmation"],
      checklist: ["HTF structure shift?", "Displacement candle?", "OB identified at source?", "Price retesting OB?", "Low volume on retest?", "Rejection candle?", "Risk 1%?"],
    },
    examples: [{ id: "ex_5", type: "winning", title: "BTC 4H OB Bounce", description: "Bitcoin displaced through resistance, retested the OB, rallied 5% in 12 hours.", screenshots: [], pnl: 3200, date: "2026-07-05" }],
    versions: [{ id: "v9", version: 1, timestamp: new Date(Date.now() - day * 40).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: false,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 40).toISOString(),
    updatedAt: new Date(Date.now() - day * 15).toISOString(),
  },
  {
    id: "pb_8",
    title: "Trend Continuation Pullback",
    description: "Enter trending markets on pullbacks to key moving averages with momentum confirmation.",
    category: "trend",
    tags: ["Trend", "Pullback", "Moving Average", "Momentum"],
    market: ["stocks", "crypto", "indices"],
    timeframes: ["1h", "4h", "1d"],
    riskProfile: "medium",
    difficulty: "beginner",
    expectedRR: 2.5,
    winRate: 65,
    totalTrades: 445,
    netProfit: 66750,
    avgRR: 2.2,
    expectancy: 0.9,
    maxDrawdown: 10,
    consistencyScore: 80,
    setup: {
      marketConditions: "Price above 200 EMA (long). 20 EMA above 50 EMA. ATR trending higher. Consistent higher highs and higher lows.",
      entryRules: ["Price pulls back to 20 EMA", "Wait for bullish/bearish candle close at EMA", "Entry on next candle push away from EMA"],
      confirmationRules: ["RSI above 50 on pullback", "Volume declining during pullback", "EMA slope still positive (long)"],
      invalidationRules: ["Price closes below 50 EMA", "EMA cross (20 below 50)", "RSI drops below 40"],
      stopLossRules: ["SL below pullback low", "SL at 1.5x ATR below entry"],
      takeProfitRules: ["TP1 at prior swing high (scale 50%)", "TP2 at 2x ATR extension (scale 30%)", "Trail remaining at 20 EMA"],
      managementRules: ["Scale 50% at TP1", "Move SL to entry after TP1", "Trail at 20 EMA for remainder"],
      riskRules: ["1.5% risk per trade", "Max 4 pullback trades per week", "Reduce size in low ATR conditions"],
      commonMistakes: ["Entering on first touch of EMA", "Ignoring EMA slope direction", "Taking trades during EMA crossover"],
      checklist: ["Trend established?", "EMA alignment bullish?", "Pullback to 20 EMA?", "Reversal candle?", "Volume declining?", "RSI above 50?", "Risk 1.5%?"],
    },
    examples: [{ id: "ex_6", type: "winning", title: "MSFT 20EMA Bounce", description: "Microsoft pulled back to 20ema on 4h, bounced perfectly, ran to new ATH.", screenshots: [], pnl: 2800, date: "2026-06-22" }],
    versions: [{ id: "v10", version: 1, timestamp: new Date(Date.now() - day * 100).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: true,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 100).toISOString(),
    updatedAt: new Date(Date.now() - day * 3).toISOString(),
  },
  {
    id: "pb_9",
    title: "Double Top/Bottom Reversal",
    description: "Trade classic double top and bottom patterns with volume confirmation and neckline breaks.",
    category: "reversal",
    tags: ["Pattern", "Reversal", "Double Top", "Double Bottom"],
    market: ["stocks", "forex", "crypto"],
    timeframes: ["1h", "4h", "1d"],
    riskProfile: "medium",
    difficulty: "beginner",
    expectedRR: 3,
    winRate: 70,
    totalTrades: 178,
    netProfit: 44500,
    avgRR: 2.8,
    expectancy: 1.4,
    maxDrawdown: 9,
    consistencyScore: 78,
    setup: {
      marketConditions: "Price making two similar highs/lows at a resistance/support level. Volume declining on second touch. RSI/MACD divergence.",
      entryRules: ["Identify two swing highs/lows at similar price level", "Wait for neckline break (middle low/high)", "Entry on retest of neckline after break"],
      confirmationRules: ["Second peak has lower volume than first", "RSI divergence between peaks", "Neckline break with above-average volume"],
      invalidationRules: ["Price makes new high/low beyond pattern", "Third peak formation (triple top/bottom)", "Volume expanding on second peak"],
      stopLossRules: ["SL beyond the second peak", "SL at 1x ATR"],
      takeProfitRules: ["TP1 at height of pattern projected from neckline", "TP2 at 1.5x pattern height"],
      managementRules: ["Scale 50% at TP1", "Move SL to entry after TP1"],
      riskRules: ["1.5% risk per trade", "No reversal against monthly trend"],
      commonMistakes: ["Not waiting for neckline retest", "Pattern too small (low timeframe noise)", "Ignoring higher timeframe trend"],
      checklist: ["Two distinct peaks/troughs?", "Similar price level?", "Volume declining on 2nd peak?", "RSI/MACD divergence?", "Neckline broken?", "Retest of neckline?", "Risk 1.5%?"],
    },
    examples: [],
    versions: [{ id: "v11", version: 1, timestamp: new Date(Date.now() - day * 50).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: false,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 50).toISOString(),
    updatedAt: new Date(Date.now() - day * 6).toISOString(),
  },
  {
    id: "pb_10",
    title: "Custom Mean Reversion Strategy",
    description: "A personalized mean reversion strategy combining Bollinger Bands, RSI, and support/resistance levels.",
    category: "custom",
    tags: ["Mean Reversion", "BB", "RSI", "S/R"],
    market: ["stocks", "futures"],
    timeframes: ["5m", "15m", "1h"],
    riskProfile: "low",
    difficulty: "beginner",
    expectedRR: 2,
    winRate: 75,
    totalTrades: 123,
    netProfit: 18450,
    avgRR: 1.8,
    expectancy: 0.9,
    maxDrawdown: 6,
    consistencyScore: 85,
    setup: {
      marketConditions: "Price touching lower Bollinger Band. RSI below 30. Price at known support level. No major news expected.",
      entryRules: ["Price touches lower BB (long) or upper BB (short)", "RSI below 30 (long) or above 70 (short)", "Entry on reversal candle close"],
      confirmationRules: ["Bullish/bearish engulfing at BB touch", "Volume spike on reversal candle"],
      invalidationRules: ["Price closes beyond BB", "RSI stays in oversold/overbought", "BB expanding (volatility breakout)"],
      stopLossRules: ["SL at 1x ATR beyond BB", "SL at nearest S/R level"],
      takeProfitRules: ["TP at middle BB (20 MA)", "Extension TP at opposite BB"],
      managementRules: ["Full exit at middle BB", "If momentum strong, scale 50% at middle BB, trail to opposite"],
      riskRules: ["0.75% risk per trade", "Max 3 mean reversion trades per day"],
      commonMistakes: ["Trading on BB expansion", "Ignoring news catalysts", "Not checking S/R confluence"],
      checklist: ["Price at BB?", "RSI extreme?", "S/R confluence?", "Reversal candle?", "Volume spike?", "No news?", "Risk 0.75%?"],
    },
    examples: [],
    versions: [{ id: "v12", version: 1, timestamp: new Date(Date.now() - day * 25).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: false,
    isArchived: false,
    createdAt: new Date(Date.now() - day * 25).toISOString(),
    updatedAt: new Date(Date.now() - day * 1).toISOString(),
  },
  {
    id: "pb_archived_1",
    title: "Old Momentum Strategy",
    description: "An older momentum strategy that has been superseded by the Opening Range Breakout.",
    category: "archived",
    tags: ["Momentum", "Legacy"],
    market: ["stocks"],
    timeframes: ["5m"],
    riskProfile: "high",
    difficulty: "intermediate",
    expectedRR: 1.5,
    winRate: 52,
    totalTrades: 89,
    netProfit: 3560,
    avgRR: 1.2,
    expectancy: 0.2,
    maxDrawdown: 25,
    consistencyScore: 45,
    setup: { marketConditions: "", entryRules: [], confirmationRules: [], invalidationRules: [], stopLossRules: [], takeProfitRules: [], managementRules: [], riskRules: [], commonMistakes: [], checklist: [] },
    examples: [],
    versions: [{ id: "v13", version: 1, timestamp: new Date(Date.now() - day * 120).toISOString(), changes: "Initial version" }],
    content: "",
    isFavorite: false,
    isArchived: true,
    createdAt: new Date(Date.now() - day * 120).toISOString(),
    updatedAt: new Date(Date.now() - day * 60).toISOString(),
  },
];
