import type { Goal, Habit, Achievement, PerformanceKpi, AiCoachMessage } from "./types";

function daysAgo(n: number) {
  const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString().split("T")[0];
}

export const mockGoals: Goal[] = [
  { id: "g1", type: "daily", category: "profit", title: "Daily Profit Target", description: "Achieve $500+ in daily realized P&L", target: 500, current: 380, unit: "$", prefix: "$", status: "active", createdAt: daysAgo(30), deadline: "Today", milestones: [{ label: "First $100", target: 100, reached: true, reachedAt: daysAgo(28) }, { label: "Halfway", target: 250, reached: true, reachedAt: daysAgo(15) }, { label: "Full Target", target: 500, reached: false }], tags: ["Profit", "Daily"], linkedHabits: ["morning_analysis", "trading_plan"] },
  { id: "g2", type: "weekly", category: "consistency", title: "Win Rate > 65%", description: "Maintain win rate above 65% for the week", target: 65, current: 72, unit: "%", status: "active", createdAt: daysAgo(60), deadline: "This Week", milestones: [{ label: "50% Win Rate", target: 50, reached: true, reachedAt: daysAgo(45) }, { label: "60% Win Rate", target: 60, reached: true, reachedAt: daysAgo(20) }, { label: "65% Target", target: 65, reached: true, reachedAt: daysAgo(7) }], tags: ["Consistency", "Weekly"], linkedHabits: ["journal_complete", "daily_review"] },
  { id: "g3", type: "monthly", category: "profit", title: "Monthly P&L $15k", description: "Achieve $15,000 in net profit for July", target: 15000, current: 12450, unit: "$", prefix: "$", status: "active", createdAt: daysAgo(90), deadline: "July 2026", milestones: [{ label: "$5k Milestone", target: 5000, reached: true, reachedAt: daysAgo(75) }, { label: "$10k Milestone", target: 10000, reached: true, reachedAt: daysAgo(30) }, { label: "Final Target", target: 15000, reached: false }], tags: ["Profit", "Monthly"], linkedHabits: ["trading_plan", "daily_review"] },
  { id: "g4", type: "monthly", category: "risk", title: "Max Drawdown < 8%", description: "Keep monthly drawdown below 8% of account", target: 8, current: 4.2, unit: "%", status: "active", createdAt: daysAgo(90), deadline: "July 2026", milestones: [{ label: "Under 10%", target: 10, reached: true, reachedAt: daysAgo(60) }, { label: "Under 8% Target", target: 8, reached: true, reachedAt: daysAgo(30) }], tags: ["Risk", "Monthly"], linkedHabits: ["replay_reviewed", "daily_review"] },
  { id: "g5", type: "quarterly", category: "psychology", title: "Psychology Score > 8/10", description: "Maintain average psychology score above 8 for Q3", target: 8, current: 7.2, unit: "/10", status: "active", createdAt: daysAgo(30), deadline: "Q3 2026", milestones: [{ label: "Score 6+", target: 6, reached: true, reachedAt: daysAgo(25) }, { label: "Score 7+", target: 7, reached: true, reachedAt: daysAgo(10) }, { label: "Target 8+", target: 8, reached: false }], tags: ["Psychology", "Quarterly"], linkedHabits: ["journal_complete", "daily_review"] },
  { id: "g6", type: "weekly", category: "education", title: "Study 5 Hours/Week", description: "Dedicate 5 hours weekly to trading education", target: 5, current: 4.5, unit: "h", status: "active", createdAt: daysAgo(60), deadline: "This Week", milestones: [{ label: "1 Hour", target: 1, reached: true }, { label: "3 Hours", target: 3, reached: true }, { label: "5 Hour Target", target: 5, reached: false }], tags: ["Education"], linkedHabits: ["replay_reviewed", "backtest_completed"] },
  { id: "g7", type: "yearly", category: "profit", title: "Annual Return 50%", description: "Achieve 50% account growth for 2026", target: 50, current: 32.5, unit: "%", status: "active", createdAt: daysAgo(180), deadline: "2026", milestones: [{ label: "Q1: 10%", target: 10, reached: true, reachedAt: daysAgo(150) }, { label: "H1: 25%", target: 25, reached: true, reachedAt: daysAgo(30) }, { label: "Q3: 40%", target: 40, reached: false }, { label: "Year: 50%", target: 50, reached: false }], tags: ["Profit", "Yearly"], linkedHabits: ["trading_plan", "daily_review", "journal_complete"] },
  { id: "g8", type: "daily", category: "habit", title: "Journal Every Trade", description: "Journal every trade taken during the day", target: 1, current: 1, unit: "", status: "active", createdAt: daysAgo(60), deadline: "Today", milestones: [{ label: "Started", target: 0, reached: true }, { label: "Complete", target: 1, reached: true }], tags: ["Habit", "Journal"], linkedHabits: ["journal_complete"] },
  { id: "g9", type: "weekly", category: "strategy", title: "Test 2 New Setups", description: "Backtest and evaluate 2 new trading setups this week", target: 2, current: 1, unit: "setups", status: "active", createdAt: daysAgo(7), deadline: "This Week", milestones: [{ label: "First Setup", target: 1, reached: true, reachedAt: daysAgo(3) }, { label: "Both Setups", target: 2, reached: false }], tags: ["Strategy", "Backtest"], linkedHabits: ["backtest_completed", "playbook_updated"] },
  { id: "g10", type: "monthly", category: "consistency", title: "200 Trades/Month", description: "Take at least 200 trades with proper risk management", target: 200, current: 156, unit: "trades", status: "active", createdAt: daysAgo(30), deadline: "July 2026", milestones: [{ label: "100 Trades", target: 100, reached: true }, { label: "150 Trades", target: 150, reached: true }, { label: "200 Target", target: 200, reached: false }], tags: ["Consistency", "Volume"], linkedHabits: ["trading_plan"] },
  { id: "g11", type: "quarterly", category: "education", title: "Complete 3 Courses", description: "Complete 3 advanced trading courses", target: 3, current: 2, unit: "courses", status: "active", createdAt: daysAgo(60), deadline: "Q3 2026", milestones: [{ label: "Course 1: ICT", target: 1, reached: true, reachedAt: daysAgo(45) }, { label: "Course 2: Order Flow", target: 2, reached: true, reachedAt: daysAgo(15) }, { label: "Course 3: Options", target: 3, reached: false }], tags: ["Education", "Learning"], linkedHabits: ["replay_reviewed", "study_session"] },
  { id: "g12", type: "yearly", category: "risk", title: "Sharpe Ratio > 2.0", description: "Maintain Sharpe ratio above 2.0 for the year", target: 2, current: 1.8, unit: "", status: "active", createdAt: daysAgo(180), deadline: "2026", milestones: [{ label: "Sharpe 1.5", target: 1.5, reached: true, reachedAt: daysAgo(120) }, { label: "Sharpe 2.0 Target", target: 2, reached: false }], tags: ["Risk", "Performance"], linkedHabits: ["daily_review"] },
  { id: "g13", type: "daily", category: "psychology", title: "Meditation 10min", description: "10-minute pre-market meditation session", target: 1, current: 0, unit: "", prefix: "", status: "missed", createdAt: daysAgo(14), deadline: "Today", milestones: [{ label: "Complete", target: 1, reached: false }], tags: ["Psychology", "Mindfulness"], linkedHabits: ["morning_analysis"] },
  { id: "g14", type: "monthly", category: "profit", title: "Reduce Commissions", description: "Reduce monthly commissions to under $500", target: 500, current: 680, unit: "$", prefix: "$", status: "active", createdAt: daysAgo(30), deadline: "July 2026", milestones: [{ label: "Under $1000", target: 1000, reached: true, reachedAt: daysAgo(20) }, { label: "Under $500", target: 500, reached: false }], tags: ["Cost", "Efficiency"], linkedHabits: ["trading_plan"] },
  { id: "g15", type: "weekly", category: "habit", title: "100% Journal Rate", description: "Journal 100% of all trades taken", target: 100, current: 88, unit: "%", status: "active", createdAt: daysAgo(30), deadline: "This Week", milestones: [{ label: "70% Rate", target: 70, reached: true, reachedAt: daysAgo(20) }, { label: "100% Target", target: 100, reached: false }], tags: ["Habit", "Journal"], linkedHabits: ["journal_complete"] },
  { id: "g16", type: "quarterly", category: "strategy", title: "Master 2 Strategies", description: "Achieve >60% win rate on 2 strategies", target: 2, current: 1, unit: "strategies", status: "active", createdAt: daysAgo(60), deadline: "Q3 2026", milestones: [{ label: "First Strategy", target: 1, reached: true, reachedAt: daysAgo(30) }, { label: "Both Strategies", target: 2, reached: false }], tags: ["Strategy", "Mastery"], linkedHabits: ["backtest_completed", "playbook_updated"] },
  { id: "g17", type: "daily", category: "education", title: "Read Trading Book", description: "Read 20 pages of trading book daily", target: 20, current: 20, unit: "pages", status: "completed", createdAt: daysAgo(5), deadline: daysAgo(1), milestones: [{ label: "10 Pages", target: 10, reached: true }, { label: "20 Pages", target: 20, reached: true, reachedAt: daysAgo(1) }], tags: ["Education", "Reading"], linkedHabits: ["morning_analysis"] },
  { id: "g18", type: "monthly", category: "consistency", title: "Trade 20 Days", description: "Trade at least 20 days this month", target: 20, current: 16, unit: "days", status: "active", createdAt: daysAgo(30), deadline: "July 2026", milestones: [{ label: "10 Days", target: 10, reached: true }, { label: "15 Days", target: 15, reached: true }, { label: "20 Target", target: 20, reached: false }], tags: ["Consistency", "Discipline"], linkedHabits: ["trading_plan"] },
  { id: "g19", type: "custom", category: "psychology", title: "No Revenge Trading", description: "Go 30 days without any revenge trade", target: 30, current: 14, unit: "days", status: "active", createdAt: daysAgo(14), deadline: "In 16 days", milestones: [{ label: "7 Days Clean", target: 7, reached: true, reachedAt: daysAgo(7) }, { label: "14 Days Clean", target: 14, reached: true, reachedAt: daysAgo(0) }, { label: "21 Days Clean", target: 21, reached: false }, { label: "30 Day Target", target: 30, reached: false }], tags: ["Psychology", "Discipline"], linkedHabits: ["journal_complete", "daily_review"] },
  { id: "g20", type: "yearly", category: "education", title: "50 Replay Sessions", description: "Review 50 trade replays this year", target: 50, current: 28, unit: "sessions", status: "active", createdAt: daysAgo(180), deadline: "2026", milestones: [{ label: "10 Replays", target: 10, reached: true, reachedAt: daysAgo(150) }, { label: "25 Replays", target: 25, reached: true, reachedAt: daysAgo(60) }, { label: "50 Target", target: 50, reached: false }], tags: ["Education", "Review"], linkedHabits: ["replay_reviewed"] },
];

export const mockHabits: Habit[] = [
  { id: "morning_analysis", label: "Morning Analysis", description: "Review overnight markets and prepare trading plan", icon: "Sun", streak: 12, bestStreak: 45, weeklyData: [true, true, true, true, true, false, false], monthlyData: Array.from({ length: 30 }, (_, i) => i < 22), category: "psychology" },
  { id: "trading_plan", label: "Trading Plan", description: "Write detailed trading plan before market open", icon: "FileText", streak: 8, bestStreak: 30, weeklyData: [true, true, false, true, true, false, false], monthlyData: Array.from({ length: 30 }, (_, i) => i < 18), category: "consistency" },
  { id: "journal_complete", label: "Journal Complete", description: "Journal every trade taken during the day", icon: "BookOpen", streak: 5, bestStreak: 22, weeklyData: [true, false, true, true, true, false, false], monthlyData: Array.from({ length: 30 }, (_, i) => i < 15), category: "habit" },
  { id: "screenshot_uploaded", label: "Screenshot Uploaded", description: "Upload chart screenshots with annotations", icon: "Camera", streak: 3, bestStreak: 12, weeklyData: [false, true, true, false, true, false, false], monthlyData: Array.from({ length: 30 }, (_, i) => i % 2 === 0), category: "habit" },
  { id: "replay_reviewed", label: "Replay Reviewed", description: "Review at least one trade replay", icon: "PlayCircle", streak: 7, bestStreak: 14, weeklyData: [true, true, true, false, true, true, false], monthlyData: Array.from({ length: 30 }, (_, i) => i < 20), category: "education" },
  { id: "backtest_completed", label: "Backtest Completed", description: "Run and analyze a backtest", icon: "FlaskConical", streak: 2, bestStreak: 8, weeklyData: [true, false, false, true, false, false, false], monthlyData: Array.from({ length: 30 }, (_, i) => i % 5 === 0), category: "strategy" },
  { id: "playbook_updated", label: "Playbook Updated", description: "Review and update strategy playbook", icon: "FileText", streak: 1, bestStreak: 5, weeklyData: [false, false, true, false, false, false, false], monthlyData: Array.from({ length: 30 }, (_, i) => i % 7 === 0), category: "strategy" },
  { id: "daily_review", label: "Daily Review", description: "End-of-day performance review and reflection", icon: "CheckCircle2", streak: 9, bestStreak: 35, weeklyData: [true, true, true, true, false, true, false], monthlyData: Array.from({ length: 30 }, (_, i) => i < 24), category: "consistency" },
];

export const mockAchievements: Achievement[] = [
  { id: "first_100_trades", title: "Century Club", description: "Execute your first 100 trades on the platform", icon: "Award", unlocked: true, unlockedAt: daysAgo(120), progress: 100, target: 100, rarity: "common" },
  { id: "seven_day_discipline", title: "7-Day Discipline", description: "Maintain a 7-day streak of complete trading routines", icon: "Flame", unlocked: true, unlockedAt: daysAgo(30), progress: 100, target: 100, rarity: "rare" },
  { id: "thirty_day_consistency", title: "30-Day Consistency", description: "Trade consistently for 30 consecutive days", icon: "Crown", unlocked: false, progress: 72, target: 100, rarity: "epic" },
  { id: "risk_master", title: "Risk Master", description: "Keep drawdown under 5% for 3 consecutive months", icon: "Shield", unlocked: true, unlockedAt: daysAgo(60), progress: 100, target: 100, rarity: "rare" },
  { id: "journal_master", title: "Journal Master", description: "Journal 500 trades with detailed annotations", icon: "BookOpen", unlocked: false, progress: 45, target: 100, rarity: "epic" },
  { id: "replay_expert", title: "Replay Expert", description: "Review 100 trade replays with AI analysis", icon: "PlayCircle", unlocked: false, progress: 28, target: 100, rarity: "legendary" },
  { id: "strategy_builder", title: "Strategy Architect", description: "Create and backtest 10 winning strategies", icon: "Layers", unlocked: true, unlockedAt: daysAgo(90), progress: 100, target: 100, rarity: "rare" },
];

export const mockKpis: PerformanceKpi[] = [
  { label: "Goal Completion", value: 73, target: 80, unit: "%", icon: "Target", trend: "up", color: "text-success" },
  { label: "Consistency Score", value: 68, target: 75, unit: "%", icon: "Activity", trend: "stable", color: "text-primary" },
  { label: "Discipline Score", value: 72, target: 80, unit: "%", icon: "Shield", trend: "up", color: "text-primary" },
  { label: "Rule Compliance", value: 85, target: 90, unit: "%", icon: "CheckCircle2", trend: "up", color: "text-success" },
  { label: "Risk Discipline", value: 78, target: 85, unit: "%", icon: "AlertTriangle", trend: "stable", color: "text-warning" },
  { label: "Avg R:R", value: 2.4, target: 3.0, unit: "", icon: "TrendingUp", trend: "up", color: "text-success" },
  { label: "Trading Streak", value: 8, target: 21, unit: "days", icon: "Flame", trend: "stable", color: "text-warning" },
  { label: "Journal Completion", value: 82, target: 100, unit: "%", icon: "BookOpen", trend: "down", color: "text-muted-foreground" },
  { label: "Review Completion", value: 65, target: 80, unit: "%", icon: "Clock", trend: "up", color: "text-primary" },
];

export const mockAiCoachMessages: AiCoachMessage[] = [
  { type: "weekly_review", title: "Weekly Performance Review", description: "Strong week with 72% win rate across 18 trades. Your discipline score improved 8 points. Focus on reducing revenge trading triggers — 2 instances detected this week.", score: 78 },
  { type: "monthly_review", title: "Monthly Progress Update", description: "July shows consistent improvement. Goal completion up 12% from June. Risk management metrics are excellent. Keep building on your morning analysis routine — it's directly correlating with better trade execution.", score: 82 },
  { type: "habit_analysis", title: "Habit Strength Analysis", description: "Your strongest habit chain is Morning Analysis → Trading Plan → Daily Review (9-day streak). Weakest link is Backtest Completed (2-day streak). Consider dedicating Sunday evenings for batch backtesting.", score: 71 },
  { type: "weakness", title: "Detected Weakness: Overtrading", description: "Pattern detected: 3 instances of taking low-probability setups after 11:30 AM. Your win rate drops from 74% (first 2 hours) to 58% (afternoon). Consider implementing a midday trading break.", score: 65 },
  { type: "strength", title: "Key Strength: Risk Management", description: "Exceptional risk control this period. Your average stop loss is 0.8% vs 1.5% target. Max single trade loss is well within parameters. This discipline preserves capital for high-conviction setups.", score: 88 },
  { type: "suggestion", title: "Recommendation: Replay Analysis", description: "You closed 3 trades early that went on to hit targets. Replay these sessions to identify the emotional triggers. Aim for 3 replay reviews this week to strengthen holding discipline.", score: null },
  { type: "motivation", title: "30-Day Journey", description: "You've maintained a trading journal for 30 consecutive days — that's in the top 10% of traders. Each entry is a brick in the foundation of your expertise. Keep building.", score: null },
];
