import type { JournalEntry, JournalTemplate } from "./types";

export const journalTemplates: JournalTemplate[] = [
  {
    id: "breakout",
    name: "Breakout Trade",
    description: "For momentum breakout setups",
    setup: "Flag Pattern",
    sections: {
      notes: "## Breakout Analysis\n\n### Pre-Trade\n- Identified resistance level:\n- Volume confirmation:\n- Market context:\n\n### Execution\n- Entry trigger:\n- Initial stop placement:\n- Profit target zones:\n\n### Post-Trade\n- What worked:\n- What didn't:\n",
      psychology: { emotion: null, energyLevel: 7, confidence: 7, discipline: 7, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 3, exitTiming: 3, riskManagement: 3, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "reversal",
    name: "Reversal Trade",
    description: "For catching reversals at key levels",
    setup: "Resistance Reject",
    sections: {
      notes: "## Reversal Analysis\n\n### Key Level\n- Identified S/R zone:\n- Confirmation candle:\n- Divergence signals:\n\n### Risk Management\n- Stop beyond swing point:\n- Risk/Reward ratio:\n- Position sizing:\n\n### Review\n",
      psychology: { emotion: null, energyLevel: 6, confidence: 6, discipline: 8, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 4, exitTiming: 3, riskManagement: 4, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "scalp",
    name: "Scalp Trade",
    description: "Quick in-and-out trades",
    setup: "Scalp",
    sections: {
      notes: "## Scalp Log\n\n### Setup\n- Timeframe:\n- Entry reason:\n- Exit reason:\n\n### Metrics\n- Time in trade:\n- Slippage:\n- Comissions:\n",
      psychology: { emotion: null, energyLevel: 8, confidence: 5, discipline: 6, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 4, exitTiming: 4, riskManagement: 2, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "swing",
    name: "Swing Trade",
    description: "Multi-day position trades",
    setup: "Pullback",
    sections: {
      notes: "## Swing Trade Plan\n\n### Thesis\n- Trend direction:\n- Entry justification:\n- Catalyst:\n\n### Management\n- Add-on zones:\n- Trailing stop plan:\n- Maximum hold time:\n\n### Result\n",
      psychology: { emotion: null, energyLevel: 5, confidence: 8, discipline: 9, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 3, exitTiming: 3, riskManagement: 4, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "earnings",
    name: "Earnings Trade",
    description: "Post-earnings momentum trades",
    setup: "Earnings",
    sections: {
      notes: "## Earnings Play\n\n### Pre-Earnings\n- Expected move:\n- IV rank:\n- Earnings history:\n\n### Post-Earnings\n- Gap direction:\n- Volume profile:\n- Gap fill probability:\n\n### Review\n",
      psychology: { emotion: null, energyLevel: 7, confidence: 6, discipline: 7, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 2, exitTiming: 3, riskManagement: 3, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
];

const now = new Date();
const d = (daysAgo: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

export const mockJournalEntries: JournalEntry[] = [
  {
    id: "je-1",
    date: d(0),
    title: "AAPL Earnings Momentum Play",
    content: "## Pre-Trade Analysis\n\nIdentified AAPL breaking above pre-market high with strong volume after earnings beat. Clear resistance level at $250 was broken with conviction.\n\n## Execution\n\nEntered at $248.20 with a limit order after the initial spike pulled back to 20EMA. Used a 1:2 risk/reward ratio with stop at $244.80.\n\n## Result\n\nTrade hit first target at $252 for partial profits. Trailing stop caught the rest at $250.40. Good execution overall.\n\n### Key Observations\n- Volume was 2x average, confirming the move\n- No major news resistance after earnings\n- Market was risk-on with tech leading\n",
    status: "published",
    tags: ["Breakout", "Earnings", "Tech"],
    session: "morning",
    marketConditions: "Risk-on, tech leading, low VIX",
    psychology: {
      emotion: "confident",
      energyLevel: 8,
      confidence: 7,
      discipline: 8,
      notes: "Felt good about this trade from the start. Despite a small pullback trigger, I held my plan and didn't let the initial -$200 drawdown shake me out.",
      triggers: ["Earnings gap", "Volume spike"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 3,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Trusting the pattern and holding through noise paid off. The pre-market preparation was the key differentiator.",
    },
    screenshots: [
      { id: "ss-1", url: "/placeholder.svg", caption: "Entry on pullback to 20EMA", type: "chart", uploadedAt: d(0) },
      { id: "ss-2", url: "/placeholder.svg", caption: "Full trade with targets", type: "chart", uploadedAt: d(0) },
    ],
    voiceNotes: [],
    linkedTrades: ["1"],
    linkedReplays: [],
    createdAt: d(0),
    updatedAt: d(0),
    templateId: "earnings",
    aiSummary: "Strong earnings momentum trade with disciplined execution. Pre-market prep and clear risk parameters contributed to success.",
    aiScore: 82,
  },
  {
    id: "je-2",
    date: d(0),
    title: "TSLA Short - Resistance Rejection",
    content: "## Setup\n\nTSLA rejected $270 resistance for the third time in two weeks. Price showed clear bearish divergence on RSI and declining volume on each test.\n\n## Entry\n\nEntered short at $268.50 after a rejection candle formed with high volume. Stop placed at $271.50 (above recent high).\n\n## Exit\n\nCovered at $264.20 when price hit the first support level. Could have held for more but the afternoon session was starting and I wanted to lock in gains.\n",
    status: "published",
    tags: ["Reversal", "Resistance", "Short"],
    session: "morning",
    marketConditions: "Mixed, low volatility session",
    psychology: {
      emotion: "patient",
      energyLevel: 7,
      confidence: 6,
      discipline: 7,
      notes: "Had to wait for the third rejection before entering. Felt the urge to jump in earlier but waited for confirmation. Patience was rewarded.",
      triggers: ["Triple top", "RSI divergence"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 3,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Waiting for multiple confirmations significantly increases probability. Three touches on resistance is a powerful signal.",
    },
    screenshots: [],
    voiceNotes: [
      { id: "vn-1", duration: 45, transcript: "TSLA rejected 270 again. Entering short with stop above recent high. Market is mixed so expecting a slow grind down.", recordedAt: d(0) },
    ],
    linkedTrades: ["2"],
    linkedReplays: [],
    createdAt: d(0),
    updatedAt: d(0),
    templateId: "reversal",
    aiSummary: "Well-executed reversal trade. Multiple confirmations (triple top, RSI divergence, volume decline) provided high-conviction entry.",
    aiScore: 88,
  },
  {
    id: "je-3",
    date: d(0),
    title: "NVDA FOMO - Lessons Learned",
    content: "## What Happened\n\nSaw NVDA ripping on no news after a quiet open. Got caught in FOMO and chased the breakout above $142.50. Price immediately reversed and stopped me out.\n\n## Mistakes\n\n1. No pre-analysis done\n2. Chased price instead of waiting for pullback\n3. Had no defined stop before entry\n4. Position size was 2x normal\n\n## Action Items\n\n1. Never trade without a plan\n2. Use limit orders, not market orders\n3. Stick to position sizing rules\n4. Wait for pullback entries on breakouts\n",
    status: "published",
    tags: ["Mistake", "FOMO", "Lesson"],
    session: "afternoon",
    marketConditions: "Low volume, choppy session",
    psychology: {
      emotion: "fomo",
      energyLevel: 9,
      confidence: 3,
      discipline: 2,
      notes: "Was feeling restless after a slow morning. Saw NVDA moving and jumped in without thinking. This is a pattern I need to break - boredom leads to revenge trading.",
      triggers: ["Missing moves", "Slow morning", "Social media hype"],
    },
    execution: {
      planFollowed: false,
      entryTiming: 1,
      exitTiming: 2,
      riskManagement: 1,
      mistake: "chased",
      mistakeNote: "Chased the breakout above $142.50 using market order. Had no pre-planned stop and ended up selling at the low of the reversal.",
      lessonLearned: "Boredom is the enemy of discipline. Never trade without a plan. If I'm bored, I should close the screens and walk away.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: ["3"],
    linkedReplays: [],
    createdAt: d(0),
    updatedAt: d(0),
    templateId: null,
    aiSummary: "FOMO/impulse trade with multiple rule violations. Recommended actions: pre-trade checklist implementation, boredom protocols, and position sizing safeguards.",
    aiScore: 25,
  },
  {
    id: "je-4",
    date: d(1),
    title: "MSFT Pullback Setup",
    content: "## Analysis\n\nMSFT pulled back to the 50EMA on the 15-minute chart after a three-day run. Volume declining on the pullback suggesting sellers were exhausted. VWAP provided additional support.\n\n## Trade Plan\n\n- Entry: Limit at $468.20 (50 EMA touch)\n- Stop: Below $465.80 (below recent swing low)\n- Target 1: $470.50 (previous resistance)\n- Target 2: $473.00 (extension)\n\n## Result\n\nPrice respected the 50EMA and bounced sharply. First target hit within two hours. Moved stop to breakeven after target 1. Second target missed by $0.30 but solid trade overall.\n",
    status: "published",
    tags: ["Pullback", "Swing", "Tech"],
    session: "morning",
    marketConditions: "Bullish trend, above-average volume",
    psychology: {
      emotion: "calm",
      energyLevel: 7,
      confidence: 7,
      discipline: 8,
      notes: "This was a textbook setup. Felt no urgency and waited for the exact entry. The preparation from the night before made execution easy.",
      triggers: ["EMA support", "Volume drying up"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 4,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Night-before preparation makes execution effortless. Never skip the pre-market routine.",
    },
    screenshots: [
      { id: "ss-3", url: "/placeholder.svg", caption: "50 EMA support with declining volume", type: "chart", uploadedAt: d(1) },
    ],
    voiceNotes: [],
    linkedTrades: ["4"],
    linkedReplays: [],
    createdAt: d(1),
    updatedAt: d(1),
    templateId: "swing",
    aiSummary: "Textbook swing trade execution. Clear entry criteria, proper risk management, and disciplined exit strategy.",
    aiScore: 90,
  },
  {
    id: "je-5",
    date: d(1),
    title: "AMZN Ascending Triangle Breakout",
    content: "## Setup\n\nAMZN formed an ascending triangle over 5 days with higher lows and flat resistance at $204. Volume was contracting - classic consolidation pattern.\n\n## Execution\n\nBought the breakout above $204.50 with volume confirmation. Added a second unit on the first pullback to $204.80 (pattern retest).\n\n## Result\n\nStrong breakout to $207 before pulling back. Scaled out 50% at $206.50 and trailed the rest. Final exit at $205.60.\n\n## Notes\n\nShould have added more on the retest. The pattern was obvious and the risk was clearly defined. Need to size up on high-confidence setups.\n",
    status: "published",
    tags: ["Breakout", "Bullish", "Pattern"],
    session: "morning",
    marketConditions: "Strong uptrend, low VIX",
    psychology: {
      emotion: "aggressive",
      energyLevel: 8,
      confidence: 8,
      discipline: 7,
      notes: "Felt very confident in this setup. The ascending triangle on AMZN is one of my highest-probability patterns. Should have committed more capital.",
      triggers: ["Ascending triangle", "Volume contraction", "Clear resistance"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 3,
      riskManagement: 3,
      mistake: "late_exit",
      mistakeNote: "Should have added more on the retest. Left significant profits on the table by scaling out too early on the second half.",
      lessonLearned: "When a high-confidence pattern presents itself, commit more capital. Scaling in on the retest of the breakout level is a proven strategy.",
    },
    screenshots: [
      { id: "ss-4", url: "/placeholder.svg", caption: "Ascending triangle on 15m chart", type: "chart", uploadedAt: d(1) },
      { id: "ss-5", url: "/placeholder.svg", caption: "Volume confirmation on breakout", type: "chart", uploadedAt: d(1) },
    ],
    voiceNotes: [],
    linkedTrades: ["5"],
    linkedReplays: [],
    createdAt: d(1),
    updatedAt: d(1),
    templateId: "breakout",
    aiSummary: "High-conviction breakout trade with proper confirmation. Pattern recognition was excellent. Opportunity for improvement in position sizing on high-confidence setups.",
    aiScore: 78,
  },
  {
    id: "je-6",
    date: d(2),
    title: "GOOGL Scalp - Impatient Entry",
    content: "## Mistake Analysis\n\nTried to scalp GOOGL after a VWAP rejection. Entered too early before confirmation. Price grinded against me for 20 minutes before I exited for a small loss.\n\n## Issue\n\nThe setup was valid but I was impatient. Had I waited for the confirmation candle to close below VWAP, the entry would have been better and the trade would have worked.\n\n## Fix\n\nAdd a one-candle confirmation rule to my scalp strategy. No entries without a confirmed signal.\n",
    status: "published",
    tags: ["Scalp", "Mistake", "Impatience"],
    session: "afternoon",
    marketConditions: "Low volatility, range-bound",
    psychology: {
      emotion: "impatient",
      energyLevel: 6,
      confidence: 4,
      discipline: 3,
      notes: "Was trying to make something happen in a slow market. The urge to trade was strong. Need to recognize when the market isn't offering good setups.",
      triggers: ["Slow market", "Desire for action", "Previous losses"],
    },
    execution: {
      planFollowed: false,
      entryTiming: 2,
      exitTiming: 3,
      riskManagement: 3,
      mistake: "early_entry",
      mistakeNote: "Entered before the VWAP rejection candle closed. Price hadn't confirmed the move yet. The small loss was deserved.",
      lessonLearned: "Impatience is expensive. If the market isn't offering setups, the best trade is no trade. Add a mandatory confirmation candle rule.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: ["6"],
    linkedReplays: [],
    createdAt: d(2),
    updatedAt: d(2),
    templateId: "scalp",
    aiSummary: "Impulse trade driven by boredom and impatience. Fix: implement forced wait for confirmation candle before entry. Consider time-based trading rules to filter low-quality setups.",
    aiScore: 35,
  },
  {
    id: "je-7",
    date: d(3),
    title: "META Post-Earnings Drift",
    content: "## Pre-Trade\n\nMETA reported after close. The stock had a history of 5+ day post-earnings drift. Pre-market showed gap up of 6% with strong volume.\n\n## Entry\n\nEntered at $512.40 on a pullback to the VWAP gap fill level. The institutional order flow was strong with 3x average volume.\n\n## Exit\n\nRode the drift for 3 days. Final exit at $528.80 using a trailing stop. Price eventually filled the gap but I was already out with a 3.2% gain.\n\n## Reflection\n\nPost-earnings drift is one of my most profitable strategies. The key is giving trades room to breathe and not cutting winners short.\n",
    status: "published",
    tags: ["Earnings", "Drift", "Swing", "Winner"],
    session: "morning",
    marketConditions: "Post-earnings volatility, high volume",
    psychology: {
      emotion: "confident",
      energyLevel: 8,
      confidence: 9,
      discipline: 9,
      notes: "This was a high-conviction trade from the start. The historical edge in post-earnings drift is clear. Felt no anxiety during the hold because I had done the research.",
      triggers: ["Earnings gap", "Historical drift pattern", "Volume confirmation"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 4,
      riskManagement: 5,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "High-conviction swing trades with historical edge should be given maximum room. Would consider using wider stops in the future to capture the full move.",
    },
    screenshots: [
      { id: "ss-6", url: "/placeholder.svg", caption: "3-day post-earnings drift", type: "chart", uploadedAt: d(1) },
      { id: "ss-7", url: "/placeholder.svg", caption: "Volume profile during hold", type: "chart", uploadedAt: d(2) },
    ],
    voiceNotes: [
      { id: "vn-2", duration: 120, transcript: "META looks strong post-earnings. Volume is 3x average and the gap fill is holding. Setting a wider trailing stop to capture the full drift. This is a textbook setup.", recordedAt: d(2) },
    ],
    linkedTrades: ["7"],
    linkedReplays: [],
    createdAt: d(3),
    updatedAt: d(1),
    templateId: "earnings",
    aiSummary: "Exceptional swing trade execution. Strong pre-trade preparation, disciplined hold through volatility, and proper trailing stop management.",
    aiScore: 92,
  },
  {
    id: "je-8",
    date: d(6),
    title: "SPY Gap Fill - Morning Range Extension",
    content: "## Pre-Trade\n\nSPY gapped down 12 points on pre-market CPI data. Identified the gap-fill level at $548.20 from yesterday's close. 9:30 AM opening candle showed aggressive buying absorbing the gap-down.\n\n## Entry\n\nEntered long at $540.80 after the 5m candle closed above the opening range high. The gap-fill was a matter of time given the volume profile.\n\n## Exit\n\nScalped 50% at $545.00 for 2.5R, trailed the rest. Final fill at $548.60 by 11:30 AM. Full gap fill in under 2 hours.\n\n## Keys to Success\n- Recognized the gap-fill pattern immediately\n- Waited for opening range confirmation (didn't buy the dip)\n- Used multiple timeframes to confirm support\n",
    status: "published",
    tags: ["Gap Fill", "SPY", "Index", "Morning"],
    session: "morning",
    marketConditions: "CPI-induced gap-down, recovery buying",
    psychology: {
      emotion: "calm",
      energyLevel: 8,
      confidence: 7,
      discipline: 9,
      notes: "Gap-down days are my bread and butter. The opening range tells you everything. Today the first 5m candle was green - that's all I needed to see.",
      triggers: ["CPI gap", "Opening range breakout", "High volume absorption"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 4,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Don't overthink gap-fills. The opening range is the most important signal of the day. If the first candle absorbs the gap, the fill is highly probable.",
    },
    screenshots: [
      { id: "ss-8", url: "/placeholder.svg", caption: "Opening range breakout after CPI gap", type: "chart", uploadedAt: d(6) },
    ],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(6),
    updatedAt: d(6),
    templateId: "scalp",
    aiSummary: "Excellent gap-fill trade with disciplined opening range confirmation. Proper use of multi-timeframe analysis and risk management.",
    aiScore: 87,
  },
  {
    id: "je-9",
    date: d(7),
    title: "NVDA Revenge Trade - $800 Lesson",
    content: "## The Screw-Up\n\nLost $250 on a bad AMD scalp in the morning. Instead of walking away, I doubled down. Went into NVDA with 3x position size trying to get it back.\n\n## The Trade\n\nBought NVDA at $895.50 after a 15-minute consolidation breakout. The breakout was real but I was 15 minutes late. By the time I got in, the smart money was selling into the strength.\n\n## The Damage\n\nNVDA reversed $12 from my entry. Held like an idiot hoping for a bounce. Finally sold at $883.20 for a -$546 loss on a trade that should have been $0. Total damage: -$796 on the day.\n\n## Root Cause\n\nNot accepting the first loss. The AMD trade was -1R, which is fine. But my ego couldn't accept a losing morning. One bad trade became a catastrophic day.\n",
    status: "published",
    tags: ["Revenge", "Mistake", "NVDA", "Oversized"],
    session: "afternoon",
    marketConditions: "Choppy, no clear direction",
    psychology: {
      emotion: "frustrated",
      energyLevel: 5,
      confidence: 2,
      discipline: 1,
      notes: "This is the worst version of myself. I knew I was making a mistake while I was making it. The voice in my head said stop but I didn't listen. Need a hard stop rule after any loss.",
      triggers: ["Morning loss", "Ego", "Desire to recover"],
    },
    execution: {
      planFollowed: false,
      entryTiming: 2,
      exitTiming: 1,
      riskManagement: 1,
      mistake: "revenge",
      mistakeNote: "Tripled position size trying to recover a small morning loss. Entered late, held through reversal, sold at the bottom. Every decision was wrong.",
      lessonLearned: "A single loss is noise. A revenge trade is a signal that I've lost control. New rule: after any -2R loss, I close the platform for the day. No exceptions.",
    },
    screenshots: [],
    voiceNotes: [
      { id: "vn-3", duration: 90, transcript: "I just blew up my morning. Took a revenge trade on NVDA after a small AMD loss. Triple size, held into reversal, sold at the bottom. This is exactly what I promised myself I wouldn't do. Need a hard stop rule. -$800 day.", recordedAt: d(7) },
    ],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(7),
    updatedAt: d(7),
    templateId: "scalp",
    aiSummary: "Classic revenge trading cascade. Multiple rule violations: oversizing, chasing, holding past stop. Critical to implement mandatory loss limits and cool-down periods.",
    aiScore: 12,
  },
  {
    id: "je-10",
    date: d(8),
    title: "TSLA Options - IV Crush Disaster",
    content: "## The Trade\n\nBought TSLA weekly calls at $275 strike, 3 DTE. Stock was $267. Earnings were in 2 days. I was betting on a pre-earnings run-up.\n\n## What Went Wrong\n\n1. Bought options during high IV\n2. Too close to expiration (3 DTE)\n3. Theta was working against me from day 1\n4. TSLA didn't move at all - just sat in a $3 range for 3 days\n\n## Result\n\nLost 85% of the position value. Stock was flat but the options decayed to near zero. -$1,200 loss.\n\n## Lesson\n\nBuying options with earnings IV premium is a sucker's game. Either sell the premium or buy longer-dated options. Weekly options near events are lottery tickets.\n",
    status: "published",
    tags: ["Options", "Mistake", "TSLA", "Earnings", "Theta"],
    session: "morning",
    marketConditions: "Low volatility, range-bound in theta week",
    psychology: {
      emotion: "frustrated",
      energyLevel: 7,
      confidence: 4,
      discipline: 5,
      notes: "Knew the risks going in but underestimated theta decay. The trade was structured poorly from the start. Should have either sold puts or bought longer-dated calls.",
      triggers: ["Options euphoria", "Underestimating time decay"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 3,
      exitTiming: 2,
      riskManagement: 2,
      mistake: "deviation",
      mistakeNote: "Deviated from my rule of only buying options with 14+ DTE. The 3 DTE was pure gambling disguised as trading.",
      lessonLearned: "Options with <7 DTE are not trades, they are bets. Stick to the 14 DTE minimum rule. If I want short-term exposure, use futures or shares.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(8),
    updatedAt: d(8),
    templateId: null,
    aiSummary: "Poor options trade structure. Buying short-dated options before earnings with elevated IV is statistically unfavorable. Need strict DTE minimums and IV rank filters.",
    aiScore: 18,
  },
  {
    id: "je-11",
    date: d(9),
    title: "AAPL 5-Minute Opening Range Scalp",
    content: "## Setup\n\nAAPL opened flat but the 5-minute opening range was tight ($0.40). Low-range opens often precede explosive moves. Waited for the break.\n\n## Entry\n\nBought the break above $243.20 (5m opening range high) with 2x volume on the breakout candle. Stop at $242.80 (below range low).\n\n## Exit\n\nFirst target $244.50 hit in 4 minutes. Scaled out 75%. Trailed the rest with a 10c stop. Final exit at $244.80.\n\n## Stats\n\n- Time in trade: 9 minutes\n- R:R Achieved: 4.5:1\n- P&L: +$340\n- Win rate on this pattern: 73% over past 3 months\n\n## Notes\n\nThis is textbook stuff. Tight range + volume breakout = high probability. These trades are mechanical now. No thinking required - just execution.\n",
    status: "published",
    tags: ["Scalp", "Opening Range", "AAPL", "Mechanical"],
    session: "morning",
    marketConditions: "Flat open, pre-FOMC calm",
    psychology: {
      emotion: "confident",
      energyLevel: 9,
      confidence: 8,
      discipline: 9,
      notes: "These are the trades I live for. The pattern recognition is so ingrained that there's no hesitation. Just see it, execute it, collect the profit.",
      triggers: ["Tight opening range", "Volume breakout", "Clean levels"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 5,
      riskManagement: 5,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "This is proof that mechanical execution beats discretionary thinking every time. The more I simplify, the more I make.",
    },
    screenshots: [
      { id: "ss-9", url: "/placeholder.svg", caption: "5m opening range breakout with volume", type: "chart", uploadedAt: d(9) },
      { id: "ss-10", url: "/placeholder.svg", caption: "Scalp execution with targets", type: "chart", uploadedAt: d(9) },
    ],
    voiceNotes: [
      { id: "vn-4", duration: 35, transcript: "Textbook opening range scalp on AAPL. Tight range, volume breakout, clean exit. 9 minutes, 4.5R. This is why I get up in the morning.", recordedAt: d(9) },
    ],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(9),
    updatedAt: d(9),
    templateId: "scalp",
    aiSummary: "Perfect mechanical execution of high-probability scalp pattern. Tight opening range + volume breakout produced 4.5R in 9 minutes. Replicate this process.",
    aiScore: 95,
  },
  {
    id: "je-12",
    date: d(10),
    title: "AMZN Breakdown - Failed Breakout Trap",
    content: "## The Trap\n\nAMZN broke above $198.50 resistance on a 15-minute chart. Looked like a textbook breakout. I went long at $198.70 with a stop at $197.80.\n\n## The Reversal\n\n15 minutes later AMZN was back below $198. Volume on the breakout was actually declining - should have noticed that. The breakout was a liquidity grab to hunt stops above resistance.\n\n## Execution\n\nGot stopped out at $197.80 for -$210 loss. Price then dropped another $4. Would have been a massive loss if I hadn't used a stop.\n\n## Analysis\n\nThe setup looked great on the surface, but the volume told the real story. Declining volume on a breakout = fakeout. Need to add a volume filter to my breakout scanner.\n",
    status: "published",
    tags: ["Breakout", "Trap", "Fakeout", "Stop Loss Saved Me"],
    session: "morning",
    marketConditions: "Low volume Friday, institutional selling",
    psychology: {
      emotion: "frustrated",
      energyLevel: 6,
      confidence: 5,
      discipline: 7,
      notes: "Frustrated that I took the trade, but proud that I respected the stop. A -1R loss is nothing. The -5R loss I avoided by having a stop is everything.",
      triggers: ["Clean resistance level", "Fake momentum"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 3,
      exitTiming: 4,
      riskManagement: 5,
      mistake: "missed_setup",
      mistakeNote: "Missed the declining volume on the breakout candle. The setup was invalid once volume confirmed the fakeout. Need a real-time volume indicator.",
      lessonLearned: "A stop loss is not a sign of weakness - it's the most important risk management tool. Also: volume confirms breakouts. No volume, no trade.",
    },
    screenshots: [
      { id: "ss-11", url: "/placeholder.svg", caption: "Fakeout breakdown - declining volume on breakout", type: "chart", uploadedAt: d(10) },
    ],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(10),
    updatedAt: d(10),
    templateId: "breakout",
    aiSummary: "Good risk management saved a bad trade. The breakout signal was invalid due to declining volume. Add volume confirmation to entry criteria.",
    aiScore: 58,
  },
  {
    id: "je-13",
    date: d(11),
    title: "MSFT Swing - 5-Day Trend Ride",
    content: "## Thesis\n\nMSFT had a clean uptrend on the daily chart since the last earnings. Higher highs, higher lows, 20EMA support. Momentum was strong with sector flows into tech.\n\n## Entry\n\nEntered at $472.40 on a 20EMA touch with declining volume on the pullback (exhaustion of sellers). This was the third touch of the 20EMA in the trend.\n\n## Management\n\nDay 1-2: Price consolidated, no action needed\nDay 3: Breakout above $476, moved stop to breakeven\nDay 4: Hit $480, scaled out 40%, moved stop to $476\nDay 5: Final exit at $484.60 on a bearish engulfing candle\n\n## Result\n\n+$2,400 on 400 shares. Held for 5 days. The trend was my friend and I stayed with it.\n\n## Why It Worked\n\n- Clear trend identification\n- Patience during consolidation days\n- Scaling out reduced anxiety\n- Letting runners run\n",
    status: "published",
    tags: ["Swing", "Trend", "MSFT", "Big Win", "Patience"],
    session: "morning",
    marketConditions: "Strong tech uptrend, low VIX",
    psychology: {
      emotion: "calm",
      energyLevel: 7,
      confidence: 8,
      discipline: 9,
      notes: "Swing trading suits my personality. There's no urgency, no noise. Just a thesis and the patience to let it play out. The 5-day hold was easy because I had a plan.",
      triggers: ["20EMA touch", "Declining volume pullback", "Sector momentum"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 4,
      riskManagement: 5,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Swing trading with clear trend is the most capital-efficient strategy I have. The daily chart filters out all the noise. Should allocate more capital to these setups.",
    },
    screenshots: [
      { id: "ss-12", url: "/placeholder.svg", caption: "5-day swing with 20EMA touches", type: "chart", uploadedAt: d(7) },
    ],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(11),
    updatedAt: d(7),
    templateId: "swing",
    aiSummary: "Outstanding swing trade execution. Clear trend, proper entry on pullback, disciplined hold, and intelligent scaling. A model for how swing trades should be managed.",
    aiScore: 94,
  },
  {
    id: "je-14",
    date: d(12),
    title: "Overnight Gap - GLD Paper Hands",
    content: "## Setup\n\nGLD gapped up $3.50 on overnight geopolitical news. Pre-market showed strong buying. The trend was already bullish from the previous week.\n\n## Entry\n\nBought at open $218.40. Price immediately faded. Within 15 minutes I was down $1.20. The gap-up was being faded by institutional selling.\n\n## Mistake\n\nI panicked. Sold at $217.20 for a -$480 loss. Price then bounced and hit $219.80 by lunch. The entire move would have been a winner if I had held.\n\n## Analysis\n\nGap-ups with geopolitical catalysts often have an initial fade as locals sell into strength, then institutions accumulate. The fade is a FEATURE, not a bug. I need to wait 30-60 minutes before deciding.\n\nNew rule: Never exit a gap trade within the first 30 minutes of open.\n",
    status: "published",
    tags: ["Gap", "GLD", "Panic", "Paper Hands", "Lesson"],
    session: "morning",
    marketConditions: "Geopolitical gap-up, high volatility",
    psychology: {
      emotion: "fearful",
      energyLevel: 5,
      confidence: 3,
      discipline: 3,
      notes: "I knew the fade was normal but I sold anyway. The fear of losing the intraday gain was too strong. Need to desensitize myself to normal pullbacks.",
      triggers: ["Initial gap fade", "Fear of losing paper profits", "Impatience"],
    },
    execution: {
      planFollowed: false,
      entryTiming: 4,
      exitTiming: 1,
      riskManagement: 2,
      mistake: "early_entry",
      mistakeNote: "Entered at market open which is fine, but exited during the normal opening range fade. Should have given the trade 30 minutes minimum before any decision.",
      lessonLearned: "Gap trades need time to develop. The first 30 minutes of open is noise, not signal. Added a hard rule: 30-minute minimum hold on gap entries.",
    },
    screenshots: [],
    voiceNotes: [
      { id: "vn-5", duration: 60, transcript: "Just paper-handed GLD for a -$480 loss. Gapped up on geopolitical news, faded at open, I sold at the exact bottom. Price bounced $2.60 after I sold. This is a pattern I need to break. New rule: 30-minute minimum hold on gap trades.", recordedAt: d(12) },
    ],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(12),
    updatedAt: d(12),
    templateId: "scalp",
    aiSummary: "Classic panicked exit during normal opening noise. The geopolitical gap-up setup was valid but execution was poor. Implement 30-minute minimum hold rule for gap trades.",
    aiScore: 30,
  },
  {
    id: "je-15",
    date: d(14),
    title: "AAPL Put Credit Spread - Theta Farm",
    content: "## Strategy\n\nSold AAPL put credit spread: Short $235 put, Long $232.50 put. 7 DTE. Collected $0.85 credit ($85 per contract). Max risk $165.\n\n## Thesis\n\nAAPL had strong support at $235 with earnings tailwind. IV was elevated at 68% (90th percentile). Time decay was in my favor.\n\n## Management\n\nDay 1-4: Theta decayed the position $0.15 per day. No management needed.\nDay 5: AAPL dipped near $235 but held. Rolled the position to the next week for additional credit.\nDay 7: Position expired worthless. Full credit collected.\n\n## Result\n\n$85 profit on $165 risk = 51.5% return in 7 days. Annualized: 268%.\n\n## Why This Works\n\n- Selling premium in high IV environments has statistical edge\n- Defined risk removes emotional management\n- Theta is the most predictable Greek\n- Rolling extends the trade without adding risk\n",
    status: "published",
    tags: ["Options", "Credit Spread", "Theta", "Passive Income"],
    session: "morning",
    marketConditions: "Bullish, elevated IV, earnings week",
    psychology: {
      emotion: "calm",
      energyLevel: 6,
      confidence: 8,
      discipline: 8,
      notes: "Options selling is a different mindset from directional trading. There's no pressure because I'm not predicting direction - I'm selling insurance. The calmest trades I take.",
      triggers: ["Elevated IV", "Support level", "Earnings season"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 5,
      riskManagement: 5,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Theta strategies are the most capital-efficient use of my trading account. The key is selling premium during IV expansion and managing by rolling, not by panicking.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(14),
    updatedAt: d(14),
    templateId: null,
    aiSummary: "Well-executed premium selling strategy. Proper position sizing, defined risk, and disciplined rolling management. Theta strategies suit the current market environment.",
    aiScore: 85,
  },
  {
    id: "je-16",
    date: d(16),
    title: "Post-FOMC Volatility Squeeze",
    content: "## Setup\n\nFOMC decision day. SPY had been compressing for 3 days before the announcement - Bollinger Bands were the tightest in 6 months. A volatility expansion was guaranteed.\n\n## Pre-Trade Plan\n\n- Identified key levels: $552 support, $558 resistance\n- Plan: Wait for the initial 5-minute post-announcement reaction\n- Strategy: Trade the first retest of the opening range after the spike\n\n## Execution\n\nInitial reaction was a spike to $560.50 (false breakout). Waited. Price came back to $556.50 and consolidated. Bought the second leg up at $557.20 with a stop below $555.80.\n\n## Exit\n\nRode the move to $561.40 over the next hour. Scaled out in thirds. Total P&L: +$680.\n\n## Key Insight\n\nThe first move after FOMC is almost always a trap. The real move is the second leg after the algos have exhausted their initial positioning.\n",
    status: "published",
    tags: ["FOMC", "Volatility", "SPY", "Macro"],
    session: "afternoon",
    marketConditions: "FOMC day, extreme volatility expansion",
    psychology: {
      emotion: "calm",
      energyLevel: 8,
      confidence: 7,
      discipline: 9,
      notes: "The key was doing nothing for the first 15 minutes. Everyone was chasing the initial spike and getting trapped. My patience was rewarded.",
      triggers: ["Bollinger squeeze", "Volume expansion", "Key level retest"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 4,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "FOMC days are profitable when you don't trade the news - you trade the market's reaction to the news. The second leg is always better than the first.",
    },
    screenshots: [
      { id: "ss-13", url: "/placeholder.svg", caption: "Post-FOMC volatility expansion setup", type: "chart", uploadedAt: d(16) },
      { id: "ss-14", url: "/placeholder.svg", caption: "Second leg entry after initial spike trap", type: "chart", uploadedAt: d(16) },
    ],
    voiceNotes: [
      { id: "vn-6", duration: 45, transcript: "FOMC day, did nothing for first 15 minutes. Initial spike was a trap as expected. Entered the second leg at $557.20. Already up $400. The second leg thesis is proven again.", recordedAt: d(16) },
    ],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(16),
    updatedAt: d(16),
    templateId: "breakout",
    aiSummary: "Superb FOMC trade execution. Recognized the initial spike as a trap and waited for the high-probability second leg. Patience and preparation were the differentiators.",
    aiScore: 91,
  },
  {
    id: "je-17",
    date: d(18),
    title: "Discipline Day - No Trades, Best Trade",
    content: "## The Decision\n\nWoke up feeling off. Slept badly, had brain fog, and the pre-market scan showed nothing I liked. The market itself was choppy with no clear direction.\n\n## The Temptation\n\nBy 10:00 AM, boredom was setting in. I saw a couple 'okay' setups on TSLA and AAPL. The urge to trade was strong.\n\n## Why I Sat Out\n\nChecked my journal: my win rate on days when I feel tired is 38%. My average loss on those days is 2.3x normal. The data doesn't lie.\n\n## Result\n\n$0 P&L. $0 in commissions. Full energy preserved for tomorrow.\n\n## Reflection\n\nNot trading when conditions aren't right is a skill. It takes more discipline to sit on your hands than to chase setups. But days like this compound into weeks of consistent performance.\n",
    status: "published",
    tags: ["Discipline", "No Trade", "Self-Awareness", "Mental Health"],
    session: "morning",
    marketConditions: "Choppy, no edge, range-bound",
    psychology: {
      emotion: "patient",
      energyLevel: 3,
      confidence: 4,
      discipline: 10,
      notes: "Proudest day of the month and I made $0. Recognizing when not to trade is the most important skill I'm developing. The data backing up my decision helped.",
      triggers: [],
    },
    execution: {
      planFollowed: true,
      entryTiming: 0,
      exitTiming: 0,
      riskManagement: 5,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Not trading is a winning trade. The market will always be there tomorrow. The only way to lose money is to trade. Need to celebrate these days as much as the winners.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(18),
    updatedAt: d(18),
    templateId: null,
    aiSummary: "Excellent display of trading discipline. Recognizing suboptimal conditions and choosing not to trade is a sign of maturity. Use journal data to reinforce this behavior.",
    aiScore: 98,
  },
  {
    id: "je-18",
    date: d(20),
    title: "Weekly Performance Review",
    content: "## Week Overview\n\nA solid week overall with 4 wins and 1 loss. The loss was entirely due to a discipline breakdown (FOMO on NVDA).\n\n## Key Metrics\n\n- Total Trades: 5\n- Win Rate: 80%\n- Avg Win: $350\n- Avg Loss: $187.50\n- Net P&L: +$1,212.50\n\n## Patterns Observed\n\n1. Morning sessions are significantly more productive than afternoon sessions\n2. Breakout setups continue to be my highest probability setup\n3. When I skip pre-market prep, my win rate drops dramatically\n\n## Goals for Next Week\n\n1. No trades after 2:00 PM\n2. Complete pre-market checklist every day\n3. Maximum 3 trades per day\n4. No position sizing above 2x normal\n",
    status: "published",
    tags: ["Review", "Weekly", "Performance"],
    session: "afternoon",
    marketConditions: "N/A",
    psychology: {
      emotion: "hopeful",
      energyLevel: 7,
      confidence: 7,
      discipline: 8,
      notes: "Good week overall. The FOMO trade on NVDA is a reminder that discipline is a daily practice. The positive weeks build confidence but the bad habits creep in when I let my guard down.",
      triggers: [],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 3,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Consistent discipline compounds. One bad trade can undo many good ones. The weekly review helps identify patterns before they become problems.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(5),
    updatedAt: d(5),
    templateId: null,
    aiSummary: "Strong weekly performance with clear self-awareness of areas for improvement. The proposed structure (time limits, trade caps, daily prep) should help maintain discipline.",
    aiScore: 75,
  },
];
