import type { JournalEntry, JournalTemplate } from "./types";

export const journalTemplates: JournalTemplate[] = [
  {
    id: "breakout",
    name: "Breakout Trade",
    description: "For momentum breakout setups",
    setup: "Flag Pattern",
    sections: {
      notes: "## Breakout Analysis\n\n### Pre-Trade\n- Identified resistance level:\n- Volume confirmation:\n- Market context:\n\n### Execution\n- Entry trigger:\n- Initial stop placement:\n- Profit target zones:\n\n### Post-Trade\n- What worked:\n- What didn't:\n",
      psychology: { emotion: null, energyLevel: 7, confidence: 7, discipline: 7, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 3, exitTiming: 3, riskManagement: 3, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "reversal",
    name: "Reversal Trade",
    description: "For catching reversals at key levels",
    setup: "Resistance Reject",
    sections: {
      notes: "## Reversal Analysis\n\n### Key Level\n- Identified S/R zone:\n- Confirmation candle:\n- Divergence signals:\n\n### Risk Management\n- Stop beyond swing point:\n- Risk/Reward ratio:\n- Position sizing:\n\n### Review\n",
      psychology: { emotion: null, energyLevel: 6, confidence: 6, discipline: 8, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 4, exitTiming: 3, riskManagement: 4, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "scalp",
    name: "Scalp Trade",
    description: "Quick in-and-out trades",
    setup: "Scalp",
    sections: {
      notes: "## Scalp Log\n\n### Setup\n- Timeframe:\n- Entry reason:\n- Exit reason:\n\n### Metrics\n- Time in trade:\n- Slippage:\n- Comissions:\n",
      psychology: { emotion: null, energyLevel: 8, confidence: 5, discipline: 6, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 4, exitTiming: 4, riskManagement: 2, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "swing",
    name: "Swing Trade",
    description: "Multi-day position trades",
    setup: "Pullback",
    sections: {
      notes: "## Swing Trade Plan\n\n### Thesis\n- Trend direction:\n- Entry justification:\n- Catalyst:\n\n### Management\n- Add-on zones:\n- Trailing stop plan:\n- Maximum hold time:\n\n### Result\n",
      psychology: { emotion: null, energyLevel: 5, confidence: 8, discipline: 9, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 3, exitTiming: 3, riskManagement: 4, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
  {
    id: "earnings",
    name: "Earnings Trade",
    description: "Post-earnings momentum trades",
    setup: "Earnings",
    sections: {
      notes: "## Earnings Play\n\n### Pre-Earnings\n- Expected move:\n- IV rank:\n- Earnings history:\n\n### Post-Earnings\n- Gap direction:\n- Volume profile:\n- Gap fill probability:\n\n### Review\n",
      psychology: { emotion: null, energyLevel: 7, confidence: 6, discipline: 7, notes: "", triggers: [] },
      execution: { planFollowed: true, entryTiming: 2, exitTiming: 3, riskManagement: 3, mistake: null, mistakeNote: "", lessonLearned: "" },
    },
  },
];

const now = new Date();
const d = (daysAgo: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

export const mockJournalEntries: JournalEntry[] = [
  {
    id: "je-1",
    date: d(0),
    title: "AAPL Earnings Momentum Play",
    content: "## Pre-Trade Analysis\n\nIdentified AAPL breaking above pre-market high with strong volume after earnings beat. Clear resistance level at $250 was broken with conviction.\n\n## Execution\n\nEntered at $248.20 with a limit order after the initial spike pulled back to 20EMA. Used a 1:2 risk/reward ratio with stop at $244.80.\n\n## Result\n\nTrade hit first target at $252 for partial profits. Trailing stop caught the rest at $250.40. Good execution overall.\n\n### Key Observations\n- Volume was 2x average, confirming the move\n- No major news resistance after earnings\n- Market was risk-on with tech leading\n",
    status: "published",
    tags: ["Breakout", "Earnings", "Tech"],
    session: "morning",
    marketConditions: "Risk-on, tech leading, low VIX",
    psychology: {
      emotion: "confident",
      energyLevel: 8,
      confidence: 7,
      discipline: 8,
      notes: "Felt good about this trade from the start. Despite a small pullback trigger, I held my plan and didn't let the initial -$200 drawdown shake me out.",
      triggers: ["Earnings gap", "Volume spike"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 3,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Trusting the pattern and holding through noise paid off. The pre-market preparation was the key differentiator.",
    },
    screenshots: [
      { id: "ss-1", url: "/placeholder.svg", caption: "Entry on pullback to 20EMA", type: "chart", uploadedAt: d(0) },
      { id: "ss-2", url: "/placeholder.svg", caption: "Full trade with targets", type: "chart", uploadedAt: d(0) },
    ],
    voiceNotes: [],
    linkedTrades: ["1"],
    linkedReplays: [],
    createdAt: d(0),
    updatedAt: d(0),
    templateId: "earnings",
    aiSummary: "Strong earnings momentum trade with disciplined execution. Pre-market prep and clear risk parameters contributed to success.",
    aiScore: 82,
  },
  {
    id: "je-2",
    date: d(0),
    title: "TSLA Short - Resistance Rejection",
    content: "## Setup\n\nTSLA rejected $270 resistance for the third time in two weeks. Price showed clear bearish divergence on RSI and declining volume on each test.\n\n## Entry\n\nEntered short at $268.50 after a rejection candle formed with high volume. Stop placed at $271.50 (above recent high).\n\n## Exit\n\nCovered at $264.20 when price hit the first support level. Could have held for more but the afternoon session was starting and I wanted to lock in gains.\n",
    status: "published",
    tags: ["Reversal", "Resistance", "Short"],
    session: "morning",
    marketConditions: "Mixed, low volatility session",
    psychology: {
      emotion: "patient",
      energyLevel: 7,
      confidence: 6,
      discipline: 7,
      notes: "Had to wait for the third rejection before entering. Felt the urge to jump in earlier but waited for confirmation. Patience was rewarded.",
      triggers: ["Triple top", "RSI divergence"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 3,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Waiting for multiple confirmations significantly increases probability. Three touches on resistance is a powerful signal.",
    },
    screenshots: [],
    voiceNotes: [
      { id: "vn-1", duration: 45, transcript: "TSLA rejected 270 again. Entering short with stop above recent high. Market is mixed so expecting a slow grind down.", recordedAt: d(0) },
    ],
    linkedTrades: ["2"],
    linkedReplays: [],
    createdAt: d(0),
    updatedAt: d(0),
    templateId: "reversal",
    aiSummary: "Well-executed reversal trade. Multiple confirmations (triple top, RSI divergence, volume decline) provided high-conviction entry.",
    aiScore: 88,
  },
  {
    id: "je-3",
    date: d(0),
    title: "NVDA FOMO - Lessons Learned",
    content: "## What Happened\n\nSaw NVDA ripping on no news after a quiet open. Got caught in FOMO and chased the breakout above $142.50. Price immediately reversed and stopped me out.\n\n## Mistakes\n\n1. No pre-analysis done\n2. Chased price instead of waiting for pullback\n3. Had no defined stop before entry\n4. Position size was 2x normal\n\n## Action Items\n\n1. Never trade without a plan\n2. Use limit orders, not market orders\n3. Stick to position sizing rules\n4. Wait for pullback entries on breakouts\n",
    status: "published",
    tags: ["Mistake", "FOMO", "Lesson"],
    session: "afternoon",
    marketConditions: "Low volume, choppy session",
    psychology: {
      emotion: "fomo",
      energyLevel: 9,
      confidence: 3,
      discipline: 2,
      notes: "Was feeling restless after a slow morning. Saw NVDA moving and jumped in without thinking. This is a pattern I need to break - boredom leads to revenge trading.",
      triggers: ["Missing moves", "Slow morning", "Social media hype"],
    },
    execution: {
      planFollowed: false,
      entryTiming: 1,
      exitTiming: 2,
      riskManagement: 1,
      mistake: "chased",
      mistakeNote: "Chased the breakout above $142.50 using market order. Had no pre-planned stop and ended up selling at the low of the reversal.",
      lessonLearned: "Boredom is the enemy of discipline. Never trade without a plan. If I'm bored, I should close the screens and walk away.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: ["3"],
    linkedReplays: [],
    createdAt: d(0),
    updatedAt: d(0),
    templateId: null,
    aiSummary: "FOMO/impulse trade with multiple rule violations. Recommended actions: pre-trade checklist implementation, boredom protocols, and position sizing safeguards.",
    aiScore: 25,
  },
  {
    id: "je-4",
    date: d(1),
    title: "MSFT Pullback Setup",
    content: "## Analysis\n\nMSFT pulled back to the 50EMA on the 15-minute chart after a three-day run. Volume declining on the pullback suggesting sellers were exhausted. VWAP provided additional support.\n\n## Trade Plan\n\n- Entry: Limit at $468.20 (50 EMA touch)\n- Stop: Below $465.80 (below recent swing low)\n- Target 1: $470.50 (previous resistance)\n- Target 2: $473.00 (extension)\n\n## Result\n\nPrice respected the 50EMA and bounced sharply. First target hit within two hours. Moved stop to breakeven after target 1. Second target missed by $0.30 but solid trade overall.\n",
    status: "published",
    tags: ["Pullback", "Swing", "Tech"],
    session: "morning",
    marketConditions: "Bullish trend, above-average volume",
    psychology: {
      emotion: "calm",
      energyLevel: 7,
      confidence: 7,
      discipline: 8,
      notes: "This was a textbook setup. Felt no urgency and waited for the exact entry. The preparation from the night before made execution easy.",
      triggers: ["EMA support", "Volume drying up"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 5,
      exitTiming: 4,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Night-before preparation makes execution effortless. Never skip the pre-market routine.",
    },
    screenshots: [
      { id: "ss-3", url: "/placeholder.svg", caption: "50 EMA support with declining volume", type: "chart", uploadedAt: d(1) },
    ],
    voiceNotes: [],
    linkedTrades: ["4"],
    linkedReplays: [],
    createdAt: d(1),
    updatedAt: d(1),
    templateId: "swing",
    aiSummary: "Textbook swing trade execution. Clear entry criteria, proper risk management, and disciplined exit strategy.",
    aiScore: 90,
  },
  {
    id: "je-5",
    date: d(1),
    title: "AMZN Ascending Triangle Breakout",
    content: "## Setup\n\nAMZN formed an ascending triangle over 5 days with higher lows and flat resistance at $204. Volume was contracting - classic consolidation pattern.\n\n## Execution\n\nBought the breakout above $204.50 with volume confirmation. Added a second unit on the first pullback to $204.80 (pattern retest).\n\n## Result\n\nStrong breakout to $207 before pulling back. Scaled out 50% at $206.50 and trailed the rest. Final exit at $205.60.\n\n## Notes\n\nShould have added more on the retest. The pattern was obvious and the risk was clearly defined. Need to size up on high-confidence setups.\n",
    status: "published",
    tags: ["Breakout", "Bullish", "Pattern"],
    session: "morning",
    marketConditions: "Strong uptrend, low VIX",
    psychology: {
      emotion: "aggressive",
      energyLevel: 8,
      confidence: 8,
      discipline: 7,
      notes: "Felt very confident in this setup. The ascending triangle on AMZN is one of my highest-probability patterns. Should have committed more capital.",
      triggers: ["Ascending triangle", "Volume contraction", "Clear resistance"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 3,
      riskManagement: 3,
      mistake: "late_exit",
      mistakeNote: "Should have added more on the retest. Left significant profits on the table by scaling out too early on the second half.",
      lessonLearned: "When a high-confidence pattern presents itself, commit more capital. Scaling in on the retest of the breakout level is a proven strategy.",
    },
    screenshots: [
      { id: "ss-4", url: "/placeholder.svg", caption: "Ascending triangle on 15m chart", type: "chart", uploadedAt: d(1) },
      { id: "ss-5", url: "/placeholder.svg", caption: "Volume confirmation on breakout", type: "chart", uploadedAt: d(1) },
    ],
    voiceNotes: [],
    linkedTrades: ["5"],
    linkedReplays: [],
    createdAt: d(1),
    updatedAt: d(1),
    templateId: "breakout",
    aiSummary: "High-conviction breakout trade with proper confirmation. Pattern recognition was excellent. Opportunity for improvement in position sizing on high-confidence setups.",
    aiScore: 78,
  },
  {
    id: "je-6",
    date: d(2),
    title: "GOOGL Scalp - Impatient Entry",
    content: "## Mistake Analysis\n\nTried to scalp GOOGL after a VWAP rejection. Entered too early before confirmation. Price grinded against me for 20 minutes before I exited for a small loss.\n\n## Issue\n\nThe setup was valid but I was impatient. Had I waited for the confirmation candle to close below VWAP, the entry would have been better and the trade would have worked.\n\n## Fix\n\nAdd a one-candle confirmation rule to my scalp strategy. No entries without a confirmed signal.\n",
    status: "published",
    tags: ["Scalp", "Mistake", "Impatience"],
    session: "afternoon",
    marketConditions: "Low volatility, range-bound",
    psychology: {
      emotion: "impatient",
      energyLevel: 6,
      confidence: 4,
      discipline: 3,
      notes: "Was trying to make something happen in a slow market. The urge to trade was strong. Need to recognize when the market isn't offering good setups.",
      triggers: ["Slow market", "Desire for action", "Previous losses"],
    },
    execution: {
      planFollowed: false,
      entryTiming: 2,
      exitTiming: 3,
      riskManagement: 3,
      mistake: "early_entry",
      mistakeNote: "Entered before the VWAP rejection candle closed. Price hadn't confirmed the move yet. The small loss was deserved.",
      lessonLearned: "Impatience is expensive. If the market isn't offering setups, the best trade is no trade. Add a mandatory confirmation candle rule.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: ["6"],
    linkedReplays: [],
    createdAt: d(2),
    updatedAt: d(2),
    templateId: "scalp",
    aiSummary: "Impulse trade driven by boredom and impatience. Fix: implement forced wait for confirmation candle before entry. Consider time-based trading rules to filter low-quality setups.",
    aiScore: 35,
  },
  {
    id: "je-7",
    date: d(3),
    title: "META Post-Earnings Drift",
    content: "## Pre-Trade\n\nMETA reported after close. The stock had a history of 5+ day post-earnings drift. Pre-market showed gap up of 6% with strong volume.\n\n## Entry\n\nEntered at $512.40 on a pullback to the VWAP gap fill level. The institutional order flow was strong with 3x average volume.\n\n## Exit\n\nRode the drift for 3 days. Final exit at $528.80 using a trailing stop. Price eventually filled the gap but I was already out with a 3.2% gain.\n\n## Reflection\n\nPost-earnings drift is one of my most profitable strategies. The key is giving trades room to breathe and not cutting winners short.\n",
    status: "published",
    tags: ["Earnings", "Drift", "Swing", "Winner"],
    session: "morning",
    marketConditions: "Post-earnings volatility, high volume",
    psychology: {
      emotion: "confident",
      energyLevel: 8,
      confidence: 9,
      discipline: 9,
      notes: "This was a high-conviction trade from the start. The historical edge in post-earnings drift is clear. Felt no anxiety during the hold because I had done the research.",
      triggers: ["Earnings gap", "Historical drift pattern", "Volume confirmation"],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 4,
      riskManagement: 5,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "High-conviction swing trades with historical edge should be given maximum room. Would consider using wider stops in the future to capture the full move.",
    },
    screenshots: [
      { id: "ss-6", url: "/placeholder.svg", caption: "3-day post-earnings drift", type: "chart", uploadedAt: d(1) },
      { id: "ss-7", url: "/placeholder.svg", caption: "Volume profile during hold", type: "chart", uploadedAt: d(2) },
    ],
    voiceNotes: [
      { id: "vn-2", duration: 120, transcript: "META looks strong post-earnings. Volume is 3x average and the gap fill is holding. Setting a wider trailing stop to capture the full drift. This is a textbook setup.", recordedAt: d(2) },
    ],
    linkedTrades: ["7"],
    linkedReplays: [],
    createdAt: d(3),
    updatedAt: d(1),
    templateId: "earnings",
    aiSummary: "Exceptional swing trade execution. Strong pre-trade preparation, disciplined hold through volatility, and proper trailing stop management.",
    aiScore: 92,
  },
  {
    id: "je-8",
    date: d(5),
    title: "Weekly Performance Review",
    content: "## Week Overview\n\nA solid week overall with 4 wins and 1 loss. The loss was entirely due to a discipline breakdown (FOMO on NVDA).\n\n## Key Metrics\n\n- Total Trades: 5\n- Win Rate: 80%\n- Avg Win: $350\n- Avg Loss: $187.50\n- Net P&L: +$1,212.50\n\n## Patterns Observed\n\n1. Morning sessions are significantly more productive than afternoon sessions\n2. Breakout setups continue to be my highest probability setup\n3. When I skip pre-market prep, my win rate drops dramatically\n\n## Goals for Next Week\n\n1. No trades after 2:00 PM\n2. Complete pre-market checklist every day\n3. Maximum 3 trades per day\n4. No position sizing above 2x normal\n",
    status: "published",
    tags: ["Review", "Weekly", "Performance"],
    session: "afternoon",
    marketConditions: "N/A",
    psychology: {
      emotion: "hopeful",
      energyLevel: 7,
      confidence: 7,
      discipline: 8,
      notes: "Good week overall. The FOMO trade on NVDA is a reminder that discipline is a daily practice. The positive weeks build confidence but the bad habits creep in when I let my guard down.",
      triggers: [],
    },
    execution: {
      planFollowed: true,
      entryTiming: 4,
      exitTiming: 3,
      riskManagement: 4,
      mistake: null,
      mistakeNote: "",
      lessonLearned: "Consistent discipline compounds. One bad trade can undo many good ones. The weekly review helps identify patterns before they become problems.",
    },
    screenshots: [],
    voiceNotes: [],
    linkedTrades: [],
    linkedReplays: [],
    createdAt: d(5),
    updatedAt: d(5),
    templateId: null,
    aiSummary: "Strong weekly performance with clear self-awareness of areas for improvement. The proposed structure (time limits, trade caps, daily prep) should help maintain discipline.",
    aiScore: 75,
  },
];
